### ISSUE TITLE
PM2 似乎无法运行吗？

### ISSUE THREAD

**Issue by Anbool** [7836246/Nuxt-Whois#1]
测试了一下似乎没办法使用 PM2 直接启动服务，我现在在项目的根目录创建了一个 start.sh 然后写入了 pnpm dev --host 127.0.0.1 使用 pm2 start start.sh --name Nuxt-Whois 才得以启动。除了 --host 参数可以定义 IP，似乎没有其他办法自定义 IP 和端口吧。
搭建测试了一下，查询速度非常快，UI 干净漂亮，感谢优秀的作品。

**Comment by 7836246** [comment]
感谢 明天会修复这个问题🙋‍♂️

**Comment by 7836246** [comment]
> 测试了一下似乎没办法使用 PM2 直接启动服务，我现在在项目的根目录创建了一个 start.sh 然后写入了 pnpm dev --host 127.0.0.1 使用 pm2 start start.sh --name Nuxt-Whois 才得以启动。除了 --host 参数可以定义 IP，似乎没有其他办法自定义 IP 和端口吧。 搭建测试了一下，查询速度非常快，UI 干净漂亮，感谢优秀的作品。

已经添加 pm2 启动配置文件 支持自定义端口 sudo pnpm pm2 start ecosystem.config.cjs

**Comment by Anbool** [comment]
> > 测试了一下似乎没办法使用 PM2 直接启动服务，我现在在项目的根目录创建了一个 start.sh 然后写入了 pnpm dev --host 127.0.0.1 使用 pm2 start start.sh --name Nuxt-Whois 才得以启动。除了 --host 参数可以定义 IP，似乎没有其他办法自定义 IP 和端口吧。 搭建测试了一下，查询速度非常快，UI 干净漂亮，感谢优秀的作品。
> 
> 已经添加 pm2 启动配置文件 支持自定义端口 sudo pnpm pm2 start ecosystem.config.cjs

我这边重新部署后发现 PM2 还是无法启动，没有找到 .output 这个文件夹
[PM2][WARN] Applications NuxtWhois not running, starting...
[PM2][ERROR] Error: Script not found: /data/Nuxt-Whois/.output/server/index.mjs

**Comment by 7836246** [comment]
> > > 测试了一下似乎没办法使用 PM2 直接启动服务，我现在在项目的根目录创建了一个 start.sh 然后写入了 pnpm dev --host 127.0.0.1 使用 pm2 start start.sh --name Nuxt-Whois 才得以启动。除了 --host 参数可以定义 IP，似乎没有其他办法自定义 IP 和端口吧。 搭建测试了一下，查询速度非常快，UI 干净漂亮，感谢优秀的作品。
> > 
> > 
> > 已经添加 pm2 启动配置文件 支持自定义端口 sudo pnpm pm2 start ecosystem.config.cjs
> 
> 我这边重新部署后发现 PM2 还是无法启动，没有找到 .output 这个文件夹 [PM2][WARN] Applications NuxtWhois not running, starting... [PM2][ERROR] Error: Script not found: /data/Nuxt-Whois/.output/server/index.mjs

sudo pnpm build 一般打包默认是在. output文件下

你之前使用的 dev 应该是开发环境下

**Comment by Anbool** [comment]
> > > > 测试了一下似乎没办法使用 PM2 直接启动服务，我现在在项目的根目录创建了一个 start.sh 然后写入了 pnpm dev --host 127.0.0.1 使用 pm2 start start.sh --name Nuxt-Whois 才得以启动。除了 --host 参数可以定义 IP，似乎没有其他办法自定义 IP 和端口吧。 搭建测试了一下，查询速度非常快，UI 干净漂亮，感谢优秀的作品。
> > > 
> > > 
> > > 已经添加 pm2 启动配置文件 支持自定义端口 sudo pnpm pm2 start ecosystem.config.cjs
> > 
> > 
> > 我这边重新部署后发现 PM2 还是无法启动，没有找到 .output 这个文件夹 [PM2][WARN] Applications NuxtWhois not running, starting... [PM2][ERROR] Error: Script not found: /data/Nuxt-Whois/.output/server/index.mjs
> 
> sudo pnpm build 一般打包默认是在. output文件下
> 
> 你之前使用的 dev 应该是开发环境下

已解决，感谢。
