### ISSUE TITLE
域名后缀不完整

### ISSUE THREAD

**Issue by chunzhimoe** [7836246/Nuxt-Whois#2]
感觉域名后缀收录的不完整啊？后缀匹配不到的能否直接请求whois.icann.org，用icann的数据库?

**Comment by 7836246** [comment]
可以手动在/server/whois/json 下的文件添加指定后缀 然后/utils/domain.ts 添加通过校验
最近没有时间 过几天可以设置更方便的方式添加同步后缀

**Comment by chunzhimoe** [comment]
那我加个pr吧，您看到之后合并下

**Comment by 7836246** [comment]
> 那我加个pr吧，您看到之后合并下

可以的

**Comment by chunzhimoe** [comment]
测试通过
https://nuxt-whois-hazel.vercel.app/

**Comment by chunzhimoe** [comment]
抱歉哈，晚了点，转换脚本出问题了

**Comment by chunzhimoe** [comment]
https://nuxt-whois-hazel.vercel.app/whois/nic_moe.html

**Comment by domainbf** [comment]
icann部分国别域名也查不到，比较全面的whois，例如tian.hu和who.cx，推荐手动添加，

**Comment by chunzhimoe** [comment]
> icann部分国别域名也查不到，比较全面的whois，例如tian.hu和who.cx，推荐手动添加，
我这里是有的，不过whois.nic.hu这个好像失效了，没办法查询到
![image](https://github.com/7836246/Nuxt-Whois/assets/60135925/63993bb6-b403-4c13-a687-93c2744d9ab5)

**Comment by domainbf** [comment]
我的意思是，
https://tian.hu/
https://who.cx/
这两个查询的比较全面，但不知道调用的方法，
而且还有价格显示。很实用。

**Comment by 7836246** [comment]
> 我的意思是， https://tian.hu/ https://who.cx/ 这两个查询的比较全面，但不知道调用的方法， 而且还有价格显示。很实用。

空了会把功能都偷过来

**Comment by domainbf** [comment]
> > 我的意思是， https://tian.hu/ https://who.cx/ 这两个查询的比较全面，但不知道调用的方法， 而且还有价格显示。很实用。
> 
> 空了会把功能都偷过来

比价网

https://tld-list.com/
https://www.nazhumi.com/
https://dot.bs
https://www.domcomp.com/
https://namebeta.com/
https://www.domnest.com/
https://tldes.com/cheapest-domains
https://www.domain265.com/
https://www.cheapestdomain.info/
有的好像有可以调用的api
