### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by chunzhimoe** [7836246/Nuxt-Whois#4]
![image](https://github.com/7836246/Nuxt-Whois/assets/60135925/22a63f77-9ceb-402e-aef9-961fccb3b6bb)
有时候直接从浏览器地址栏复制，复制之后要手动删除域名前后面的这些东西，感觉很不方便。能否增加一个识别功能?直接识别后缀之后查询?

**Comment by 7836246** [comment]
> ![image](https://private-user-images.githubusercontent.com/60135925/317635297-22a63f77-9ceb-402e-aef9-961fccb3b6bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTUyOTEsIm5iZiI6MTcxMTg1NDk5MSwicGF0aCI6Ii82MDEzNTkyNS8zMTc2MzUyOTctMjJhNjNmNzctOWNlYi00MDJlLWFlZjktOTYxZmNjYjNiNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAzMTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NjBlYzI4YzJjMjdhMGMwZjRjYjI2YTE2YjI4ZmQzNTlmYWNlYmE0Y2RlNzRiY2ZmYTMyMDQ1NjcxOWE1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JNNHPDTqeFomXgbZ-s5bolh46XTPPtzHuqxAIRNHxYQ) 有时候直接从浏览器地址栏复制，复制之后要手动删除域名前后面的这些东西，感觉很不方便。能否增加一个识别功能?直接识别后缀之后查询?

收到 我空了会调整 目前在找工作
